name=Oleoleg_ULN2003_Stepper
version=1.0.0
author=Oleoleg (Oleg Shiryaev) 
sentence=Stepper Motor Driver Library
paragraph=Stepper Motor (28BYJ-48) connected to ULN2003 IC
category=Other
url=https://github.com/oleoleg/Oleoleg_ULN2003_Stepper
architectures=*
includes=Oleoleg_ULN2003_Stepper.h
